src/Entity/Groupe.php
<?php

namespace App\Entity;

use App\Repository\GroupeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;

/**
 * @author ZONCHELLO Sébastien
 * Cette classe représente un channel qui peut être soit public, privé ou un DM
 */

/**
 * @ORM\Entity(repositoryClass=GroupeRepository::class)
 */
class Groupe
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\ManyToOne(targetEntity=TypeGroupe::class, inversedBy="groupes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $TypeGroupeId;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="GroupesCrees")
     * @ORM\JoinColumn(nullable=false)
     */
    private $IdProprietaire;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateCreation;

    /**
     * @ORM\OneToMany(targetEntity=Invitation::class, mappedBy="GroupeId")
     */
    private $invitations;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="GroupeId")
     */
    private $messages;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isDeleted;

    /**
     * @ORM\OneToMany(targetEntity=Notification::class, mappedBy="Groupe")
     */
    private $notifications;

    public function __construct(EntityManager $entityManager=null)
    {
            $this->invitations = new ArrayCollection();
            $this->messages = new ArrayCollection();
            $this->notifications = new ArrayCollection();
    }

    public function getFormattedGroupe() {
        return [
            "id" => $this->getid(),
            "nom" => $this->getNom(),
            "id_proprietaire" => $this->getIdProprietaire()->getId(),
            "date_creation" => $this->getDateCreation(),
            "description" => $this->getDescription(),
            "type_groupe" => $this->getTypeGroupeId()->getFormattedTypeGroupe()
        ];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getTypeGroupeId(): ?TypeGroupe
    {
        return $this->TypeGroupeId;
    }

    public function setTypeGroupeId(?TypeGroupe $TypeGroupeId): self
    {
        $this->TypeGroupeId = $TypeGroupeId;

        return $this;
    }

    public function getIdProprietaire(): ?User
    {
        return $this->IdProprietaire;
    }

    public function setIdProprietaire(?User $IdProprietaire): self
    {
        $this->IdProprietaire = $IdProprietaire;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->DateCreation;
    }

    public function setDateCreation(\DateTimeInterface $DateCreation): self
    {
        $this->DateCreation = $DateCreation;

        return $this;
    }

    /**
     * @return Collection|Invitation[]
     */
    public function getInvitations(): Collection
    {
        return $this->invitations;
    }

    public function addInvitation(Invitation $invitation): self
    {
        if (!$this->invitations->contains($invitation)) {
            $this->invitations[] = $invitation;
            $invitation->setGroupeId($this);
        }

        return $this;
    }

    public function removeInvitation(Invitation $invitation): self
    {
        if ($this->invitations->contains($invitation)) {
            $this->invitations->removeElement($invitation);
            // set the owning side to null (unless already changed)
            if ($invitation->getGroupeId() === $this) {
                $invitation->setGroupeId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setGroupeId($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getGroupeId() === $this) {
                $message->setGroupeId(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getIsDeleted(): ?bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(bool $isDeleted): self
    {
        $this->isDeleted = $isDeleted;
        return $this;
    }

    /**
     * @return Collection|Notification[]
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications[] = $notification;
            $notification->setGroupe($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->removeElement($notification)) {
            if ($notification->getGroupe() === $this) {
                $notification->setGroupe(null);
            }
        }

        return $this;

    }

}

src/Controller/WebsocketController.php
<?php

namespace App\Controller;

use App\Entity\Invitation;
use App\Form\UploadFileType;
use Monolog\Logger;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Statut;
use App\Entity\Notification;
use Psr\Log\LoggerInterface;
use Gos\Bundle\WebSocketBundle\Pusher\Wamp\WampPusher;
use Gos\Bundle\WebSocketBundle\Pusher\PusherInterface;

class WebsocketController extends AbstractController
{

    private LoggerInterface $logger;
    private EntityManager $entityManager;
    private $pusher;

    public function __construct(EntityManagerInterface $entityManager, LoggerInterface $logger, PusherInterface $wampPusher)
    {
        $this->entityManager = $entityManager;
        $this->logger = $logger;
        $this->pusher = $wampPusher;
    }

    /**
     * @author VATHONNE Thomas
     * Permet de récupérer toutes les informations reliées à l'utilisateur et de générer le formulaire d'envoie de médias
     * @Route("/app", name="app")
     */
    public function index()
    {
        $user = $this->getUser();

        if($user->getFirstConnection()){
            return $this->redirectToRoute('userChangePassword');
        }
        
        $emInvitation = $this->entityManager->getRepository(Invitation::class);

        $fileForm = $this->createForm(UploadFileType::class,null);
        $emNotifications = $this->entityManager->getRepository(Notification::class);
        
        if( $user->getStatut()->getName() == "Hors Ligne") {
            $user->setStatut($this->getDoctrine()->getRepository(Statut::class)->findOneBy( array('id' => 1)));
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
            $em->refresh($user);
        }
        $this->pusher->push(["typeEvent" => "statutChange", "data" => ["user" => ["id" => $user->getId()], "statut" => $user->getStatut()->getFormattedStatus()]], "userevent_topic", ["idUser" => $user->getId(), "typeEvent" => "statut"], []);

        return $this->render('websocket/index.html.twig', [
            'controller_name' => 'WebsocketController',
            'channels' => [
                "publiques" => $emInvitation->getChannelUtilisateur(1, $user->getId()),
                "prives" => $emInvitation->getChannelUtilisateur(2, $user->getId()),
                "dm" => $emInvitation->getDMChannels($user->getId())
            ],
            'user' => [
                "id" => $this->getUser()->getId(),
                "pseudo" => $this->getUser()->getPseudo(),
                "statut" => $this->getUser()->getStatut()->getName(),
                "photo_de_profile" => $this->getUser()->getFileName(),
                "statut_color" => $this->getUser()->getStatut()->getStatusColor()
            ],
            'fileForm' => $fileForm->createView(),
            'notifications'=>[
                'nbgroupes'=>count($emNotifications->getNotificationsGroupes($user->getId())),
                'groupes'=> $emNotifications->getNotificationsGroupes($user->getId()),
                'nbmessages'=> count($emNotifications->getNotificationsMessages($user->getId())),
                'messages'=> $emNotifications->getNotificationsMessages($user->getId()),
            ]
        ]);
    }

}

templates/websocket/_channel_infos.html.twig
<div id="channel-infos-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Infos du channel</h5>
                <button type="button" style="font-size: 24px; color:white;" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="channel-infos-loader">
                    <span class="arrow-span">↓</span>
                    <span class="arrow-span" style="--delay: 0.1s">↓</span>
                    <span class="arrow-span" style="--delay: 0.3s">↓</span>
                    <span class="arrow-span" style="--delay: 0.4s">↓</span>
                    <span class="arrow-span" style="--delay: 0.5s">↓</span>
                </div>
                <div id="channel-infos-modal-body" class="channel-description">
                    <ul class="nav nav-tabs" id="anotherTab" role="tablist">
                        <li class="nav-item"><a class="nav-link active" id="channel-infos-tab" data-toggle="tab" href="#print-channel" role="tab" aria-controls="print-channel" aria-selected="true">Afficher infos</a></li>
                        <li class="nav-item"><a class="nav-link" id="edit-infos-tab" data-toggle="tab" href="#edit-channel" role="tab" aria-controls="edit-channel" aria-selected="false">Modifier infos</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade active show in" id="print-channel" role="tabpanel" aria-labelledby="edit-infos-tab">
                            <div class="infos-card">
                                <h1 id="channel-title-info" class="infos-card__title"></h1>
                                <p id="channel-creation-info" class="card-text text-muted"></p>
                                <p id="channel-owner-info" class="infos-card__description"></p>
                                <p id="channel-description-info" class="infos-card__description"></p>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="edit-channel" role="tabpanel" aria-labelledby="channel-infos-tab">
                            {{ form_start(form, {'attr': {'id': 'channel-infos-update-form'}}) }}
                                <div class="form-group row">
                                    {{ form_label(form.nom, null, {
                                        'label': 'Titre',
                                        'label_attr': {'class': 'col-lg-3'}
                                    }) }}
                                    {{ form_widget(form.nom, {'attr': {'class': "col-lg-7" }}) }}
                                </div>

                                <div class="form-group row">
                                    {{ form_label(form.description, null, {
                                        'label': 'Description',
                                        'label_attr': {'class': 'col-lg-3'}
                                    }) }}
                                    {{ form_widget(form.description, {'attr': {'class': "col-lg-7"}}) }}
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label form-control-label"></label>
                                    <div class="col-lg-7 update-btn-group">
                                        {{ form_widget(form.annuler, {'label': "Annuler", 'attr': {'class': "btn btn-secondary cancel-button"}}) }}
                                        {{ form_widget(form.confirmer, {'label': "Confirmer", 'attr': {'class': "btn change-button"}}) }}
                                    </div>
                                </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 

<div id="contact-infos-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Infos du contact</h5>
                <button type="button" style="font-size: 24px; color:white;" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="contact-infos-loader">
                    <span class="arrow-span">↓</span>
                    <span class="arrow-span" style="--delay: 0.1s">↓</span>
                    <span class="arrow-span" style="--delay: 0.3s">↓</span>
                    <span class="arrow-span" style="--delay: 0.4s">↓</span>
                    <span class="arrow-span" style="--delay: 0.5s">↓</span>
                </div>
                <div id="contact-infos-modal-body" class=" card-col col-sm-12">
                    <div class="card shadow user-card w-100">
                        <div class="card-body row">
                            <div class="col-12 col-sm-3 mb-3 mb-sm-0 text-center">
                                <div class="img-content">
                                    <img id="contact-pdp-info" class="thumb-lg rounded-circle bx-s" src="" alt="">
                                    <i id="contact-status-info" class="fa fa-circle"></i>
                                </div>
                            </div>
                            <div class="col-12 col-sm-9">
                                <div class="user-info" style="padding-left: 20px;">
                                    <h4 id="contact-name-info"></h4>
                                    <p id="contact-profession-info" class="text-muted"></p>
                                    <hr>
                                    <p id="contact-pseudo-info"></p>
                                    <p id="contact-mail-info"></p>
                                    <p id="contact-age-info"></p>
                                    <p id="contact-departement-name-info"></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 

<div id="leaveChannelModal" class="modal fade">
	<div class="modal-dialog modal-confirm">
		<div class="modal-content">
			<div class="modal-header flex-column">
				<h4 class="modal-title w-100">Quitter le channel</h4>	
			</div>
			<div class="modal-body">
				<p>Etes-vous sûr(e) de vouloir quitter ce channel ?</p>
			</div>
			<div class="modal-footer justify-content-end">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
				<button id="confirm-leave-channel" type="button" class="btn btn-danger">Quitter</button>
			</div>
		</div>
	</div>
</div>

templates/websocket/_contact.html.twig
<div id="annuaire-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h3>Annuaire
            </h3>
            <button type="button" style="font-size: 24px; color:white;" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="input-group">
                            <input type="text" id="annuaire-input-group1" name="annuaire-input-group1" class="form-control" placeholder="Rechercher un utilisateur">
                            <span class="input-group-text search-button">
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="row ml-md-0 mb-2 p-t-10 d-flex align-content-stretch flex-wrap" id="listUsers">
                </div>
                <div id="listUsersPagination">
                </div>
            </div>
        </div>
    </div>
  </div>
</div>

templates/websocket/_create_groupe.html.twig
<div class="col-1 pl-0 pr-0">
    <div id="create-grp-modale{{groupe.typeGroupeId.id}}" class="modal fade create-grp-modale" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Créer un groupe</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="container-fluid user-profile-container">
                        <div >
                            <div class="col-lg-12">
                                {{ form_start(form, {'attr': {'id': "groupe-create-form#{groupe.typeGroupeId.id}",'class':'groupe-create-form'}}) }}
                                    <div class="form-group row">
                                        {{ form_label(form.nom, null, {
                                            'label_attr': {'class': 'col-lg-3'}
                                        }) }}
                                        {{ form_widget(form.nom, {'attr': {'class': "col-lg-7 create_groupe_nom"}}) }}
                                    </div>
                                    <div class="form-group row">
                                        {{ form_label(form.description, null, {
                                            'label_attr': {'class': 'col-lg-3'}
                                        }) }}
                                        {{ form_widget(form.description, {'attr': {'class': "col-lg-7 create_groupe_description"}}) }}
                                    </div>
                                    <div class="form-group row">
                                        {{ form_label(form.typeGroupeId, null, {
                                            'label_attr': {'class': 'col-lg-3'}
                                        }) }}

                                        {{ form_widget(form.typeGroupeId, {'attr': {'class': "col-lg-7 create_groupe_typeGroupeId"}}) }}
                                    </div>
                                    <div class="form-group row" id="invits{{groupe.typeGroupeId.id}}">
                                        {{ form_label(form.invitations, null, {
                                            'label_attr': {'class': 'col-lg-3'}
                                        }) }}
                                        <div class="col-lg-7">
                                            <input type="text" id="searchContact{{groupe.typeGroupeId.id}}" class="searchContact"/>
                                            {{ form_widget(form.invitations, {'attr': {'class': "create_groupe_invitations",'data-live-search':"true"}}) }}
                                        </div>
                                    </div>
                                    <div class="form-group row center">
                                        <label class="col-lg-3 col-form-label form-control-label"></label>
                                        <div class="col-lg-7 update-btn-group">
                                            {{ form_widget(form.confirmer,{'label': "Confirmer", 'attr': {'class': "btn change-button"}}) }}
                                        </div>
                                    </div>
                                {{ form_end(form) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/websocket/_create_groupe_public.html.twig
<div id="create-grp-modale2" class="modal fade create-grp-modale" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Nouveau groupe public</h5>
                <button type="button" style="font-size: 24px; color:white;" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="channel-description">
                    <ul class="nav nav-tabs" id="publicChannelTab" role="tablist">
                        <li class="nav-item"><a class="nav-link active" id="channel-public-tab" data-toggle="tab" href="#print-channel-public" role="tab" aria-controls="print-channel-public" aria-selected="true">Rejoindre un groupe</a></li>
                        <li class="nav-item"><a class="nav-link" id="create-channel-tab" data-toggle="tab" href="#create-channel-public" role="tab" aria-controls="create-channel-public" aria-selected="false">Créer un groupe</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade active show in" id="print-channel-public" role="tabpanel" aria-labelledby="channel-public-tab">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="input-group">
                                            <input type="text" id="annuaire-input-group2" name="annuaire-input-group2" class="form-control" placeholder="Rechercher un groupe">
                                            <span class="input-group-text search-button">
                                                <i class="fa fa-search"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row ml-md-0 mb-2 p-t-10 d-flex align-content-stretch flex-wrap" id="listGrps">
                                </div>
                                <div id="listGrpsPagination">
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="create-channel-public" role="tabpanel" aria-labelledby="create-channel-tab">
                            {{ form_start(form, {'attr': {'id': "groupe-create-form#{groupe.typeGroupeId.id}",'class':'groupe-create-form'}}) }}
                                    <div class="form-group row">
                                        {{ form_label(form.nom, null, {
                                            'label_attr': {'class': 'col-lg-3'}
                                        }) }}
                                        {{ form_widget(form.nom, {'attr': {'class': "col-lg-7 create_groupe_nom"}}) }}
                                    </div>
                                    <div class="form-group row">
                                        {{ form_label(form.description, null, {
                                            'label_attr': {'class': 'col-lg-3'}
                                        }) }}
                                        {{ form_widget(form.description, {'attr': {'class': "col-lg-7 create_groupe_description"}}) }}
                                    </div>
                                    <div class="form-group row">
                                        {{ form_label(form.typeGroupeId, null, {
                                            'label_attr': {'class': 'col-lg-3'}
                                        }) }}

                                        {{ form_widget(form.typeGroupeId, {'attr': {'class': "col-lg-7 create_groupe_typeGroupeId"}}) }}
                                    </div>
                                    <div class="form-group row">
                                        {{ form_label(form.invitations, null, {
                                            'label_attr': {'class': 'col-lg-3'}
                                        }) }}
                                        {{ form_widget(form.invitations, {'attr': {'class': "col-lg-7 create_groupe_invitations"}}) }}
                                    </div>
                                    <div class="form-group row center">
                                        <label class="col-lg-3 col-form-label form-control-label"></label>
                                        <div class="col-lg-7 update-btn-group">
                                            {{ form_widget(form.confirmer,{'label': "Confirmer", 'attr': {'class': "btn change-button"}}) }}
                                        </div>
                                    </div>
                                {{ form_end(form) }}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div> 

templates/websocket/_message_options.html.twig
<div id="deleteMessageModal" class="modal fade">
    <div class="modal-dialog modal-confirm">
        <div class="modal-content">
            <div class="modal-header flex-column">
                <h4 class="modal-title w-100">Supprimer le message</h4>	
            </div>
            <div class="modal-body">
                <p>Etes-vous sûr(e) de vouloir supprimer ce message ?</p>
            </div>
            <div class="modal-footer justify-content-end">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                <button id="confirm-delete-message" type="button" class="btn btn-danger">Supprimer</button>
            </div>
        </div>
    </div>
</div>

<div id="modifyMessageModal" class="modal fade">
    <div class="modal-dialog modal-confirm">
        <div class="modal-content">
            <div class="modal-header flex-column">
                <h4 class="modal-title w-100">Modifier le message</h4>	
            </div>
            {{ form_start(updateMessageForm, {'attr': {'id': 'message-update-form'}}) }}
            <div class="modal-body">
                {{ form_widget(updateMessageForm.message, {'attr': {'cols': 62, 'rows': 5 }}) }}
            </div>
            <div class="modal-footer justify-content-end">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                {{ form_widget(updateMessageForm.confirmer, {'label': "Modifier", 'attr': {'class': "btn modify-btn"}}) }}
            </div>
            {{ form_end(updateMessageForm) }}
        </div>
    </div>
</div>